server:
  port: 8023
#应用名称（nacos会将该名称作为服务的名称注册）
spring:
  application:
    name: nacos-product
    #配置nacos地址
  main:
    #允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        #nacos的默认账号密码就是nacos
        password: nacos
        username: nacos
        #命名空间可以用来将服务隔离在各个不同的空间中方便管理
        #例如可以格利城dev fat等
        namespace: public
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=true&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: Qq123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#这是mybatis所使用的配置
mybatis:
  type-aliases-package: com.tuling.springcloud.orders.domain
  mapper-locations: classpath*:mappers/*.xml
  #使用mybatis有两个重要的配置：1:mapper-locations:告诉mybatisSQL的映射文件在这里
  #2:type-aliases-package:告诉mybatis对应的实体类位置
#  #数据库连接配置
#  spring.datasource.url=jdbc:mysql://127.0.0.1:3306/mybatis_plus
#  spring.datasource.username=root
#  spring.datasource.password=Qq123456
#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver